(require 'setup-dired)

(declare-function ta-aw-other-window-scroll-buffer "ext:kb-browse")
(declare-function ta-scroll-up-half-window "ext:kb-browse")
(declare-function ta-scroll-down-half-window "ext:kb-browse")

(define-key dired-mode-map (kbd "'") 'dired-mark)
(define-key dired-mode-map (kbd "t") 'dired-toggle-marks)
(define-key dired-mode-map (kbd "u") 'dired-unmark)
(define-key dired-mode-map (kbd "k") 'dired-do-kill-lines)
(define-prefix-command 'ta-dired-mark-map)
(define-key ta-dired-mark-map (kbd "r") 'dired-mark-files-regexp)
(define-key ta-dired-mark-map (kbd "e") 'dired-mark-extension)
(define-key ta-dired-mark-map (kbd "d") 'dired-mark-directories)
(define-key ta-dired-mark-map (kbd "u") 'dired-unmark-all-marks)
(define-key dired-mode-map (kbd ":") 'ta-dired-mark-map)

(define-key dired-mode-map (kbd "v") 'dired-view-file)
(define-key dired-mode-map (kbd "y") 'dired-show-file-type)
(define-key dired-mode-map (kbd "!") 'dired-do-shell-command)
(define-key dired-mode-map (kbd "&") 'dired-do-async-shell-command)
(define-key dired-mode-map (kbd "=") 'dired-diff)
(define-key dired-mode-map (kbd "g") 'revert-buffer)
(define-key dired-mode-map (kbd "L") 'dired-do-load)

(define-key dired-mode-map (kbd "d") 'ta-scroll-up-half-window)
(define-key dired-mode-map (kbd "s") 'ta-scroll-down-half-window)

(define-key dired-mode-map (kbd "i") 'dired-up-directory)
(define-key dired-mode-map (kbd "p") 'dired-previous-line)
(define-key dired-mode-map (kbd "n") 'dired-next-line)
(define-key dired-mode-map (kbd "C-M-p") 'dired-prev-dirline)
(define-key dired-mode-map (kbd "C-M-n") 'dired-next-dirline)
(define-key dired-mode-map (kbd "M-)") 'dired-next-marked-file)
(define-key dired-mode-map (kbd "M-(") 'dired-next-marked-file)

(define-key dired-mode-map (kbd "+") 'dired-create-directory)
(define-key dired-mode-map (kbd "r") 'dired-do-rename)
(define-key dired-mode-map (kbd "c") 'dired-do-copy)
(define-key dired-mode-map (kbd "<up>") 'dired-flag-file-deletion)
(define-key dired-mode-map (kbd "x") 'dired-do-flagged-delete)
(define-key dired-mode-map (kbd "w") 'dired-copy-filename-as-kill)
(define-key dired-mode-map (kbd "S") 'dired-do-symlink)
(define-key dired-mode-map (kbd "R") 'dired-do-relsymlink)

(define-prefix-command 'ta-dired-find-file-map)
(define-key ta-dired-find-file-map (kbd "e") 'ta-dired-aw-find-file)
(define-key ta-dired-find-file-map (kbd "p") 'ta-dired-aw-find-file-split-up)
(define-key ta-dired-find-file-map (kbd "n") 'ta-dired-aw-find-file-split-down)
(define-key ta-dired-find-file-map (kbd "b") 'ta-dired-aw-find-file-split-left)
(define-key ta-dired-find-file-map (kbd "f") 'ta-dired-aw-find-file-split-right)
(define-key ta-dired-find-file-map (kbd "'") 'dired-do-find-marked-files)
(define-key dired-mode-map (kbd "e") 'ta-dired-find-file-map)

(define-key dired-mode-map (kbd "]") 'ta-dired-subtree-toggle-all)
(define-key dired-mode-map (kbd "<tab>") 'dired-subtree-toggle)
(define-key dired-mode-map (kbd "/") 'dired-subtree-cycle)
(define-key dired-mode-map (kbd "<backspace>") 'dired-subtree-remove)
(define-key dired-mode-map (kbd "(") 'dired-subtree-up)
(define-key dired-mode-map (kbd "C-p") 'dired-subtree-previous-sibling)
(define-key dired-mode-map (kbd "C-n") 'dired-subtree-next-sibling)

(define-key dired-mode-map (kbd "[") 'dired-hide-details-mode)
(define-key dired-mode-map (kbd ".") 'dired-hide-dotfiles-mode)
(define-key dired-mode-map (kbd ">") 'dired-narrow)
(define-key dired-mode-map (kbd ",") 'dired-collapse-mode)
(define-key dired-mode-map (kbd "<down>") 'dired-toggle-sudo)
(define-key dired-mode-map (kbd "M-s") 'swiper)
(define-key dired-mode-map (kbd ")") 'ta-aw-other-window-scroll-buffer)
(define-key dired-mode-map (kbd "<SPC>") 'peep-dired)
(define-key peep-dired-mode-map (kbd "_") 'peep-dired-aw-window)
(define-key peep-dired-mode-map (kbd "C-n") nil)
(define-key peep-dired-mode-map (kbd "C-p") nil)
(define-key peep-dired-mode-map (kbd "<up>") nil)
(define-key peep-dired-mode-map (kbd "<down>") nil)
(define-key peep-dired-mode-map (kbd "<SPC>") nil)
(define-key peep-dired-mode-map (kbd "<backspace>") nil)
(define-key peep-dired-mode-map (kbd "q") nil)
(define-key peep-dired-mode-map (kbd "p") 'peep-dired-prev-file)
(define-key peep-dired-mode-map (kbd "n") 'peep-dired-next-file)
(define-key peep-dired-mode-map (kbd "<prior>") 'peep-dired-scroll-page-up)
(define-key peep-dired-mode-map (kbd "<next>") 'peep-dired-scroll-page-down)

(global-set-key (kbd "M-]") 'ta-sidebar)


(provide 'kb-dired)
